---
stages:
  - build
  - test
  - docker
  - publish

image: golang:1.15.1

services:
  - docker:18.09.7-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE: sbressey/aws-sqs-operator

build:
  stage: build
  except:
    - tags
  script:
    - make manager

test:
  stage: test
  except:
    - tags
  script:
    - make test

build_branch:
  stage: docker
  image: docker:19.03.1
  allow_failure: true
  dependencies:
    - build
  when: manual
  only:
    - branches
  except:
    - tags
    - master
  script:
    - docker build -t ${IMAGE}:${CI_COMMIT_SHORT_SHA} .
    - trivy --exit-code 0 --ignore-unfixed --severity HIGH,CRITICAL ${IMAGE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${IMAGE}:${CI_COMMIT_SHORT_SHA}

build_master:
  stage: docker
  image: docker:19.03.1
  allow_failure: true
  dependencies:
    - build
  only:
    - master
  except:
    - tags
  script:
    - docker build -t ${IMAGE}:latest .
    - trivy --exit-code 0 --ignore-unfixed --severity HIGH,CRITICAL ${IMAGE}:latest
    - docker push ${IMAGE}:latest

publish:
  stage: publish
  image: docker:19.03.1
  only:
    - tags
  script:
    - docker pull ${IMAGE}:latest
    - docker tag ${IMAGE}:latest ${IMAGE}:${CI_COMMIT_TAG}
    - docker push ${IMAGE}:${CI_COMMIT_TAG}
