---
apiVersion: v1
kind: Service
metadata:
  name: metrics
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
  selector:
    app: aws-sqs-operator
---
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: aws-sqs-operator
  name: metrics-monitor
  namespace: default
spec:
  endpoints:
    - path: /metrics
      port: metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: aws-sqs-operator