
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - queuing.aws.artifakt.io
  resources:
  - sqs-queues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - queuing.aws.artifakt.io
  resources:
  - sqs-queues/status
  verbs:
  - get
  - patch
  - update
