# permissions for end users to edit sqs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqs-editor-role
rules:
- apiGroups:
  - queuing.aws.artifakt.io
  resources:
  - sqs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - queuing.aws.artifakt.io
  resources:
  - sqs/status
  verbs:
  - get
